### ISSUE TITLE
Please update tdjson

### ISSUE THREAD

**Issue by Demetriy** [leoMehlig/TDJSON#2]
Hello! Unfortunately, I have some problems with compiling the original code, so your repository saved me for the development time, please update the code to the current one, thanks!

**Comment by istarchenkov** [comment]
> Hello! Unfortunately, I have some problems with compiling the original code, so your repository saved me for the development time, please update the code to the current one, thanks!

Привет, можно тебе написать куда-то, есть вопросы как собрать либу

**Comment by leoMehlig** [comment]
@Demetriy I also have problems right now. Unfortunately it always take very long to test small changes in the build process. I will try to figure out how to fix it and maybe even try to automate it in travis.org. For the time being: If you can find some time you could help me, but trying to run the commands in the .travis.yml and see if you can fix the issues. If you have any questions, text me @leoMehlig on Telegram.

**Comment by WingedDoom** [comment]
@leoMehlig Hey, I've been playing around with build scripts provided by Telegram team and the one lying in your repo. I managed to build latest TDLib version (from Telegram's repo) using official build scripts, which I slightly changed.

Python apple support dropped armv7 and arm7s architectures support and as I figured from TDLib repo issues, TDLib developers recommend changing `git checkout 2.7` to `git checkout 60b990128d5f1f04c336ff66594574515ab56604` in `build-openssl.sh`.

After changing that I've built OpenSSL and TDLib successfully, and obtained needed static libraries using parts of your `build.sh` script, and then just replacing old `.a` files in TDJSON's `lib` folder with new ones. So I believe if you just change line 5 in your `build.sh` as I described above, you will get your script to build too.

Unfortunately I'm not very experienced with CIs in general and Travis in particular yet, so I can't help you with `.travis.yml` stuff.

**Comment by leoMehlig** [comment]
I still get:
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
CMake Warning at CMakeLists.txt:249 (message):
  Not found OpenSSL: skip TDLib, tdactor, tdnet, tddb
```

@WingedDoom Do you know how to fix this?
﻿﻿

**Comment by WingedDoom** [comment]
Hmm. Somehow OpenSSL, which builds in the beginning of your build script, is not found. I'll look into it more thoroughly in the following couple of days.

**Comment by leoMehlig** [comment]
Just a small update. I got the project to build again with td v1.4.0. ATM I'm testing if the Carthage build also works. I just wasn't able to setup travis to build automatically, because the build take >2 hours and thats the limit for travis. If anyone nows how to speed up the build or any other solutions, they would be very welcome!

**Comment by leoMehlig** [comment]
New release is online.
