### ISSUE TITLE
libswiftcore.dylib issue using pre build framework

### ISSUE THREAD

**Issue by arpit2438735** [leoMehlig/TDJSON#3]
@leoMehlig Thanks for providing the pre build framework.But while adding it, it throws an error

`dyld library not loaded @rpath/libswiftcore.dylib reason image not found`.

Attached the screenshot as well
<img width="1680" alt="screenshot 2018-12-20 at 09 58 19" src="https://user-images.githubusercontent.com/398390/50329205-20dba700-051c-11e9-89b9-2e014cbc7110.png">

iOS Simulator Version - 10.2
Xcode - 10

**Comment by leoMehlig** [comment]
@arpit2438735 This looks like you didn't include the framwork correctly. could you send my a sample project with this build error?

**Comment by arpit2438735** [comment]
@leoMehlig Shall I send the  `.xcodeproj`. That works for you or shall I send a whole project?

**Comment by leoMehlig** [comment]
Please zip the whole folder and send it. It githube doesn’t work, you can also send it to @leoMehlig via Telegram.

**Comment by arpit2438735** [comment]
Thanks for your help. I will send you soon.

**Comment by jwktje** [comment]
Just a status update, as I've spoken to you all and I thought it would be handy to have everything in the issue.

@leoMehlig sent me: 
> According to the logs it can’t find some Symbol in the swift standard lib. Specifically the string struct
Maybe you can try to remove all swift code form the project that might fix it

I've reached out to @EddyVerbruggen who has experience in using native code in NativeScript. He might have a little time to advice what a possible fix would be. 

In the meantime the best way forward I think would be to check and see if the framework could work without any Swift code, like Leo suggests. 

Also for reference. The issue occurs when testing [this {N} plugin.](https://github.com/arpit2438735/nativescript-tglib) (Currently in development)

**Comment by leoMehlig** [comment]
Any updates?

**Comment by jwktje** [comment]
The plugin works, but they also released a web-based version on the last release from Telegram.
I'm still experimenting with what the best fit is going forward, as both work but are on different platforms. 

This project is also a volunteer project so sadly can't have much priority. But what's relevant to you Leo, the issue can be closed :) Thanks for the help
