### ISSUE TITLE
Version 1.5.0

### ISSUE THREAD

**Issue by koraykoska** [leoMehlig/TDJSON#5]
Could you bump to version 1.5.0 for tdlib 1.5.0? Thanks.

**Comment by leoMehlig** [comment]
I'm working on it 😄

**Comment by leoMehlig** [comment]
I currently get errors when building v1.5.0. I've created an issue on [tdlib-737](https://github.com/tdlib/td/issues/737)

**Comment by leoMehlig** [comment]
v1.5.0 is released. Make sure to redownload the libtdcore.a.

**Comment by koraykoska** [comment]
Thanks
