### ISSUE TITLE
Incompatible with Firebase Analytics

### ISSUE THREAD

**Issue by koraykoska** [leoMehlig/TDJSON#6]
Somehow TDJSON is incompatible with Firebase Analytics because of the custom sqlite. I don't have a clue why but Firebase complains about an sqlite problem and can't initialise its database.

**Comment by leoMehlig** [comment]
Very strange!?! But since I only build [tdlib](https://github.com/tdlib/td) and can't control stuff like that, you probably have to raise that issue there. Sorry

**Comment by koraykoska** [comment]
You know, I solved it but I can‘t really tell why. I just had to remove
TDJSON from the linked libraries in XCode.

TDLib-iOS was still in the list and used TDJSON as it should. I just
removed the explicit link for my app.

I guess for people using TdJSON directly this is not an option but if
someone else is using TDLib, this might be helpful.

@Zimonzk can explain why this happens and why removing it from the linked
libraries fixes it.
